### ISSUE TITLE
cellulose degrading genes questions

### ISSUE THREAD

**Issue by xhxlilium** [AnantharamanLab/METABOLIC#104]
I successfully run the pipeline, and found three cellulose degrading genes,
but one of them called cellulase, with KO id K01779
![image](https://user-images.githubusercontent.com/44562411/192098774-f492b889-3219-462b-9f6c-aa63900fde79.png)

but this gene seems to participate in D-amino acid metabolism but not cellulose degrading, and I could not find a reference
link this gene with cellulose degrading. If it truly happens, could you provide me the evidence such as a reference?

**Comment by ChaoLab** [comment]
I have updated this row: K01179 and K20542 for cellulase. The package of "METABOLIC_template_and_database.tgz" has been updated, you can replace the old one and have a try
