### ISSUE TITLE
run_to_setup.sh step 7

### ISSUE THREAD

**Issue by pur80a** [AnantharamanLab/METABOLIC#107]
**Describe the bug**
When running `run_to_setup.sh` the download of pepunit.lib fails. 

**To Reproduce**
1. `wget https://github.com/AnantharamanLab/METABOLIC/archive/refs/tags/v4.0.tar.gz`
2. `tar xf v4.0.tar.gz && cd METABOLIC-4.0`
3. `conda env create -f /METABOLIC_v4.0_env.yml && conda activate metabolic-v4.0`
4. `bash run_to_setup.sh`

**Expected behavior**
download successfully pepunit.lib

**Solution**
When I use the commands from step 7 from the [wiki](https://github.com/AnantharamanLab/METABOLIC/wiki/Installation#Full_installation) to download, it works: 
```
wget ftp://ftp.ebi.ac.uk/pub/databases/merops/current_release/pepunit.lib
```
instead of 
```
curl --silent ftp://ftp.ebi.ac.uk/pub/databases/merops/current_release/pepunit.lib -O pepunit.lib
``` 
which is used in `run_to_setup.sh` from the archive

**Comment by ChaoLab** [comment]
Many thanks! Just updated

**Comment by pur80a** [comment]
Great! Thanks!
