### ISSUE TITLE
bash run_to_setup.sh getting stuck

### ISSUE THREAD

**Issue by Marlinski95** [AnantharamanLab/METABOLIC#110]
Hi! 
I am trying to install METABOLIC using conda and everything worked so far. However, I am having issues with the run_to_setup.sh as it get's stuck in the motif downloading step.

`Motif/cytochrome_c_oxidase_genes/04.mafft.pl`

I saw a similar issue in a previous report suggesting gdown to be the problem so I re-installed it in my environment but it didn't fix the problem. It has been like this for hours and I am unsure on what to do. Could you assist?

Best,
Marlene

**Comment by Calvin2077** [comment]
I am having the same problem! If I can ask did you figure out how to get around this issue? If so, can I please have some help.

**Comment by ChaoLab** [comment]
Hi, it could be the version upgrading issue of gdown. In the yml file (https://github.com/AnantharamanLab/METABOLIC/blob/master/METABOLIC_v4.0_env.yml), I have updated it to gdown==4.6.0. Can you try upgrading your gdown?

**Comment by Calvin2077** [comment]
Hello thank you very much for your help it is much appreciated. I have tried doing this to no success.
