### ISSUE TITLE
Can't locate List/MoreUtils.pm in @INC

### ISSUE THREAD

**Issue by huizhen-yan** [AnantharamanLab/METABOLIC#112]
I followed the instructions for a full installation, but i always got this error:

`[zhanglab@biostack METABOLIC]$ perl METABOLIC-C.pl -help
Can't locate List/MoreUtils.pm in @INC (you may need to install the List::MoreUtils module) (@INC contains: /biostack/bioconda/lib/site_perl/5.26.2/x86_64-linux-thread-multi /biostack/bioconda/lib/site_perl/5.26.2 /biostack/bioconda/lib/5.26.2/x86_64-linux-thread-multi /biostack/bioconda/lib/5.26.2 .) at /biostack/bioconda/lib/site_perl/5.26.2/Statistics/Descriptive/Full.pm line 14.
BEGIN failed--compilation aborted at /biostack/bioconda/lib/site_perl/5.26.2/Statistics/Descriptive/Full.pm line 14.
Compilation failed in require at /biostack/bioconda/lib/site_perl/5.26.2/Statistics/Descriptive.pm line 18.
BEGIN failed--compilation aborted at /biostack/bioconda/lib/site_perl/5.26.2/Statistics/Descriptive.pm line 18.
Compilation failed in require at METABOLIC-C.pl line 40.
BEGIN failed--compilation aborted at METABOLIC-C.pl line 40.
[zhanglab@biostack METABOLIC]$

[zhanglab@biostack METABOLIC]$ conda install -c bioconda perl-list-moreutils
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Retrieving notices: ...working... done
[zhanglab@biostack METABOLIC]$ perl METABOLIC-C.pl -help
Can't locate List/MoreUtils.pm in @INC (you may need to install the List::MoreUtils module) (@INC contains: /biostack/bioconda/lib/site_perl/5.26.2/x86_64-linux-thread-multi /biostack/bioconda/lib/site_perl/5.26.2 /biostack/bioconda/lib/5.26.2/x86_64-linux-thread-multi /biostack/bioconda/lib/5.26.2 .) at /biostack/bioconda/lib/site_perl/5.26.2/Statistics/Descriptive/Full.pm line 14.
BEGIN failed--compilation aborted at /biostack/bioconda/lib/site_perl/5.26.2/Statistics/Descriptive/Full.pm line 14.
Compilation failed in require at /biostack/bioconda/lib/site_perl/5.26.2/Statistics/Descriptive.pm line 18.
BEGIN failed--compilation aborted at /biostack/bioconda/lib/site_perl/5.26.2/Statistics/Descriptive.pm line 18.
Compilation failed in require at METABOLIC-C.pl line 40.
BEGIN failed--compilation aborted at METABOLIC-C.pl line 40.
[zhanglab@biostack METABOLIC]$ gcc -v
`

Could you help me?

**Comment by ChaoLab** [comment]
It will be problematic to have a full installation. Did you try the conda installation (https://github.com/AnantharamanLab/METABOLIC/wiki/Installation#anaconda-environment)?
