### ISSUE TITLE
mkdir: cannot create directory

### ISSUE THREAD

**Issue by B-1991-ing** [AnantharamanLab/METABOLIC#120]
Hi Zhichao, 

No any other output folder generated except the pre-selfgenerated intermediate_files. Could you help me have a look?

**METABOLIC_log.log.zip**
[METABOLIC_log.log.zip](https://github.com/AnantharamanLab/METABOLIC/files/10490695/METABOLIC_log.log.zip)

<img width="1354" alt="Screenshot 2023-01-24 at 15 09 12" src="https://user-images.githubusercontent.com/54441633/214316344-2e6db5ef-b70e-4052-84fc-ebb7d109129f.png">

Best,

Bing

**Comment by patriciatran** [comment]
It looks from the log that there is a permission denied error where it's trying to make the directory. Can you specify a new location where you know for you have read and write permissions? Let us know how this goes. Thanks

**Comment by B-1991-ing** [comment]
Thank you for your reply. 

I solved this issue by changing the part of the directory name from "metabolic_c_oms-D1" to  "metabolic_c_oms_D1". It works now.
