### ISSUE TITLE
Provided .yml file is missing r-diagram 

### ISSUE THREAD

**Issue by DininduSenanayake** [AnantharamanLab/METABOLIC#126]
**Describe the bug**
Provided https://github.com/AnantharamanLab/METABOLIC/blob/master/METABOLIC_v4.0_env.yml  is missing **r-diagram** package. 
This will interfere with rendering the reports correctly 

**Solution**
Add **r-diagram=1.6.4** to .yml file

I have created a[ PR for this ](https://github.com/AnantharamanLab/METABOLIC/commit/f942e155b98c20c479454957a60df249ecdf86d9)

**Comment by patriciatran** [comment]
Thanks, I just accepted your PR :)
