### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by joeyclancy** [AnantharamanLab/METABOLIC#127]
hello METABOLIC Team

When I run  `env create -f METABOLIC_v4.0_env.yml`, it comes

`Encountered problems while solving.
Problem: nothing provides __unix needed by pysocks-1.7.1-pyha2e5f31_6`

what should i do?

sincerely

**Comment by ChaoLab** [comment]
I have no idea what is the problem. I guess maybe because of the conda version?

**Comment by joeyclancy** [comment]
> I have no idea what is the problem. I guess maybe because of the conda version?

yes it is... Thanks !
cheers
