### ISSUE TITLE
Thresholds?

### ISSUE THREAD

**Issue by tnn111** [AnantharamanLab/METABOLIC#13]
Can someone tell me where to find the thresholds used for the hmms? I've been trying to figure out where the cutoff for something like amoA is set and I don't easily see it. I know it's a TIGRFAM you use, but I don't know if you are using TCs or an E-value.

**Comment by ChaoLab** [comment]
Hi, tnn111, we use TC/NC as the threshold. The TC/NC value could be found in each HMM file.

**Comment by patriciatran** [comment]
Hi @tnn111 does this answer your question? the TC/NC value are in the "METABOLIC_hmm_db" folder, and in the .hmm files. Here is an example for amoA. If so, we will close the issue. Thank you.
<img width="911" alt="Screen Shot 2020-04-29 at 1 16 23 PM" src="https://user-images.githubusercontent.com/16926887/80631631-a1b58780-8a1b-11ea-838a-8f5c82d4fc41.png">

**Comment by tnn111** [comment]
Patricia,

You can close the issue. Thanks.

Torben
