### ISSUE TITLE
the difference between Func1 and Func2 in the MW-score_result_table_input.txt

### ISSUE THREAD

**Issue by haihao999** [AnantharamanLab/METABOLIC#132]
Hi,
Could you tell me what is the difference between Func1 and Func2 in the MW-score_result_table_input.txt? 
Because I want to add the function I follow to count the MW scores
Thank you!

**Comment by NataliHB** [comment]
Hi, 

I am wondering the same. Also is there a way to get MW score at bin level? I try with the taxonomy, flag at species level but since most of my MAGs are not resolved up species, the results are very skewed. 
Many thanks

**Comment by ChaoLab** [comment]
> 

How many bins are there in your analysis?

**Comment by ChaoLab** [comment]
> Hi,
> 
> I am wondering the same. Also is there a way to get MW score at bin level? I try with the taxonomy, flag at species level but since most of my MAGs are not resolved up species, the results are very skewed. Many thanks

Hi, Can I know how many bins are there in your analysis?

**Comment by NataliHB** [comment]
> > Hi,
> > I am wondering the same. Also is there a way to get MW score at bin level? I try with the taxonomy, flag at species level but since most of my MAGs are not resolved up species, the results are very skewed. Many thanks
> 
> Hi, Can I know how many bins are there in your analysis?

It's a small dataset of 126 bins

**Comment by ChaoLab** [comment]
>

**Comment by ChaoLab** [comment]
> > > Hi,
> > > I am wondering the same. Also is there a way to get MW score at bin level? I try with the taxonomy, flag at species level but since most of my MAGs are not resolved up species, the results are very skewed. Many thanks
> > 
> > 
> > Hi, Can I know how many bins are there in your analysis?
> 
> It's a small dataset of 126 bins

I will have a look at the code to see if I can go down to get MW scores for bins

**Comment by ChaoLab** [comment]
I made changes to both `METABOLIC-C.pl` and `METABOLIC-C.2nd_run.pl` scripts. You can set "bin" (using MAG itself to calculate MW-score) to "-tax" to have a test

**Comment by NataliHB** [comment]
> I made changes to both `METABOLIC-C.pl` and `METABOLIC-C.2nd_run.pl` scripts. You can set "bin" (using MAG itself to calculate MW-score) to "-tax" to have a test

Thank you so much for this! I will try it now! :)

**Comment by NataliHB** [comment]
> METABOLIC-C.2nd_run.pl



> > I made changes to both `METABOLIC-C.pl` and `METABOLIC-C.2nd_run.pl` scripts. You can set "bin" (using MAG itself to calculate MW-score) to "-tax" to have a test
> 
> Thank you so much for this! I will try it now! :)



> > I made changes to both `METABOLIC-C.pl` and `METABOLIC-C.2nd_run.pl` scripts. You can set "bin" (using MAG itself to calculate MW-score) to "-tax" to have a test
> 
> Thank you so much for this! I will try it now! :)

I used the METABOLIC-C.2nd_run.pl and worked smoothly, I got now the MW score at bin level. Many thanks!
