### ISSUE TITLE
Missing bam files

### ISSUE THREAD

**Issue by Drob84761** [AnantharamanLab/METABOLIC#138]
It looks like this is missing the bam files which makes sense because I dont get an output for MW. I installed with conda. Any idea?

Renaming POLAR_LAKES12/All_gene_collections.gene.scaffold.rev.2.bt2.tmp to POLAR_LAKES12/All_gene_collections.gene.scaffold.rev.2.bt2
rm: cannot remove ‘POLAR_LAKES12/*.bam’rm: cannot remove ‘POLAR_LAKES12/*.bam’: No such file or directory
: No such file or directory
rm: cannot remove ‘POLAR_LAKES12/*.sorted.stat’rm: cannot remove ‘POLAR_LAKES12/*.sorted.stat’: No such file or directory
: No such file or directory
rm: cannot remove ‘POLAR_LAKES12/*.bai’rm: cannot remove ‘POLAR_LAKES12/*.bai’: No such file or directory
: No such file or directory
[2023-05-04 00:16:58] Drawing element cycling diagrams finished
[2023-05-04 00:16:58] Drawing metabolic handoff diagrams...
[2023-05-04 00:17:12] Drawing metabolic handoff diagrams finished

**Comment by ChaoLab** [comment]
It seems that the step of metagenomic reads mapping did not work. 
From `POLAR_LAKES12/.bam`, I guess something is wrong with your reads input txt file. Did you follow the instruction mentioned here (https://github.com/AnantharamanLab/METABOLIC/wiki/METABOLIC-Usage#all-required-and-optional-flags)? Do you have a blank line in the reads input txt file?

**Comment by Drob84761** [comment]
Yes! I had a typo in the file! I corrected it to look like this 

#Read pairs:
/home/fslcollab273/compute/POLAR_LAKES_RAW/CLEAN_READS_BAC/FRX11MBac_1.fastq,/home/fslcollab273/compute/POLAR_LAKES_RAW/CLEAN_READS_BAC/FRX11MBac_2.fastq
/home/fslcollab273/compute/POLAR_LAKES_RAW/CLEAN_READS_BAC/FRX6MBac_1.fastq,/home/fslcollab273/compute/POLAR_LAKES_RAW/CLEAN_READS_BAC/FRX6MBac_2.fastq
/home/fslcollab273/compute/POLAR_LAKES_RAW/CLEAN_READS_BAC/FRX8MBac_1.fastq,/home/fslcollab273/compute/POLAR_LAKES_RAW/CLEAN_READS_BAC/FRX8MBac_2.fastq
/home/fslcollab273/compute/POLAR_LAKES_RAW/CLEAN_READS_BAC/WLB10MBac_1.fastq,/home/fslcollab273/compute/POLAR_LAKES_RAW/CLEAN_READS_BAC/WLB10MBac_2.fastq
/home/fslcollab273/compute/POLAR_LAKES_RAW/CLEAN_READS_BAC/WLB17MBac_1.fastq,/home/fslcollab273/compute/POLAR_LAKES_RAW/CLEAN_READS_BAC/WLB17MBac_2.fastq
/home/fslcollab273/compute/POLAR_LAKES_RAW/CLEAN_READS_BAC/WLB5MBac_1.fastq,/home/fslcollab273/compute/POLAR_LAKES_RAW/CLEAN_READS_BAC/WLB5MBac_2.fastq

And my line of code looks like this

perl METABOLIC-C.pl -in-gn /home/fslcollab273/compute/POLAR_LAKES_RAW/INITIAL_BINNING/metabat2_bins_refined_METABOLIC -r ReadPairs.txt -o POLAR_LAKES12 -t 75

Is that looking correct?

**Comment by Drob84761** [comment]
Do I need to run these samples one at a time? It seems like the community network figure has bunched all my samples together.

**Comment by ChaoLab** [comment]
Yes, you can either run all your sample at once or each for one time

**Comment by Drob84761** [comment]
Ok so if I was looking for differences between samples then I would want to run them one at a time. Right? Thank you so much for responding so quickly

**Comment by ChaoLab** [comment]
Yes
