### ISSUE TITLE
Nutrient diagrams only generated for the first genome and unopenable

### ISSUE THREAD

**Issue by osvatic** [AnantharamanLab/METABOLIC#139]
Hello,

I am using the Metabolic-C workflow of Metabolic v4.0. I used the workflow with ~50 MAGs. The Nutrient_Cycling_Diagram only contains 1 output file. 

Here is the command I used: 
`perl /home/apps/conda/miniconda3/envs/metabolic-4.0/METABOLIC/METABOLIC-C.pl -in-gn Metabolic_C/MAGs -r Metabolic_C/READS_LOCATION.txt -rt metaG -st illumina -t 32 -tax family -p meta -o Metabolic_C_family`

This also happens when running the command with -tax set to genus or phylum. 

Is there a way to fix this?

**Comment by ChaoLab** [comment]
It is unnormal, some parts might not work properly. The `-tax` option will not influence the figure result. Did you check the log file and the output folders to make sure all the results are good?

**Comment by osvatic** [comment]
The log and run log do not seem to indicate any errors. Both are attached. A perl locale issue pops up in the log but that is system wide and doesn't cause problems.

I compared all of the outputs that I generated to the example outputs and it looks like everything else is there. The "METABOLIC_Figures" directory has all files that is should just missing the Nutrient_Cycling_Diagrams. 


[METABOLIC_log.log](https://github.com/AnantharamanLab/METABOLIC/files/11430831/METABOLIC_log.log)
[METABOLIC_run.log](https://github.com/AnantharamanLab/METABOLIC/files/11430832/METABOLIC_run.log)

**Comment by ChaoLab** [comment]
Are all files in `METABOLIC_Figures_Input/Nutrient_Cycling_Diagram_Input` correct?
![image](https://github.com/AnantharamanLab/METABOLIC/assets/35715202/9f8e8e3d-e209-4882-881c-293e6265d763)

If these are correct, I suggest to find the corresponding line for generating those R figures to make a test (under your METABOLIC conda environment of course)

**Comment by osvatic** [comment]
Yes, I have 1 of those files for each MAG and the Total.R_input.txt

![image](https://github.com/AnantharamanLab/METABOLIC/assets/20932225/cd67171c-666b-477a-a790-1ac06969fc08)

I found the Rscript line and tested it. 
```
[osvatic@login01 Metabolic_C_family]$ Rscript /apps/conda/miniconda3/envs/metabolic-4.0/METABOLIC/draw_biogeochemical_cycles.R METABOLIC_Figures_Input/Nutrient_Cycling_Diagram_Input test/ TRUE
During startup - Warning messages:
1: Setting LC_TIME failed, using "C" 
2: Setting LC_MONETARY failed, using "C" 
3: Setting LC_PAPER failed, using "C" 
4: Setting LC_MEASUREMENT failed, using "C" 
[1] "test//draw_biogeochem_cycles"
[1] "There are: 78 genomes to process"
[1] "INDIV_JMF_2107_07_0001_metabat_cov.13"
Error in library(diagram) : there is no package called ‘diagram’
Calls: drawNcycle.single -> library
Execution halted
```

Looks like I am just missing a package (probably more).

**Comment by ChaoLab** [comment]
Maybe that is the problem! Hope this will solve the issue

**Comment by osvatic** [comment]
Worked! No idea why that wasn't installed.
