### ISSUE TITLE
mv: cannot stat 'HiC_baj/Output_energy_flow/Energy_plot/network.plot.pdf': No such file or directory

### ISSUE THREAD

**Issue by Sharifah89** [AnantharamanLab/METABOLIC#140]
**Describe the bug**
I run the command 

perl METABOLIC-C.pl -in-gn ]path to my bins folder] -r [path to filtered reads of shot gun metagenomics for sample 1, not contigs (forward)],  [path to filtered reads of shot gun metagenomics for sample 1, not contigs (Reverse)],[path to filtered reads of shot gun metagenomics for sample 2, not contigs (forward)],  [path to filtered reads of shot gun metagenomics for sample 2, not contigs (Reverse)]-o output dir

The result of the MW_SCORE_RESULT is empty. the community plot is also blank. The Functional_network_figures is empty. 

I also got the following error not sure if they are related:
rm: cannot remove 'HiC_baj/*.bam': No such file or directory
rm: cannot remove 'HiC_baj/*.sorted.stat': No such file or directory
rm: cannot remove 'HiC_baj/*.bai': No such file or directory

![Screen Shot 1402-02-19 at 02 55 53](https://user-images.githubusercontent.com/129158100/236962702-84ca6bf7-e927-4b53-ade3-3d31dc74fccc.png)

![Screen Shot 1402-02-19 at 02 55 39](https://user-images.githubusercontent.com/129158100/236962682-682bda60-7729-47a9-b854-3d9a3101d259.png)

**Comment by ChaoLab** [comment]
It seems that your input reads txt file has some issues. Did you check if there are any empty lines? Are all the paths to reads files correct and the full paths?

**Comment by Sharifah89** [comment]
solved 
I needed to write the paths to my reads in a text file and just write it after -r 
worked well

**Comment by mahesh1368569** [comment]
Hi Sharifah89,

Could you please attach the text file? I have encountered same issue, i want to know how you prepared text file.

Thanks

**Comment by Sharifah89** [comment]
Hello, 
Sorry for the late reply
In the text file arrange your R1 and R2 reads and separate them with a comma. Like this example:

/ibex/project/c2211/filtered_reads/combined/Baj_1_filt_R1.fq,/ibex/project/c2211/filtered_reads/combined/Baj_1_filt_R2.fq
/ibex/project/c2211/filtered_reads/combined/Baj_2_filt_R1.fq,/ibex/project/c2211/filtered_reads/combined/Baj_2_filt_R2.fq
/ibex/project/c2211/filtered_reads/combined/Baj_3_filt_R1.fq,/ibex/project/c2211/filtered_reads/combined/Baj_3_filt_R2.fq
/ibex/project/c2211/filtered_reads/combined/Bea_3_filt_R1.fq,/ibex/project/c2211/filtered_reads/combined/Bea_3_filt_R2.fq
/ibex/project/c2211/filtered_reads/combined/D_1_filt_R1.fq,/ibex/project/c2211/filtered_reads/combined/D_1_filt_R2.fq
/ibex/project/c2211/filtered_reads/combined/D_2_filt_R1.fq,/ibex/project/c2211/filtered_reads/combined/D_2_filt_R2.fq
/ibex/project/c2211/filtered_reads/combined/D_3_filt_R1.fq,/ibex/project/c2211/filtered_reads/combined/D_3_filt_R2.fq
/ibex/project/c2211/filtered_reads/combined/FS_1_filt_R1.fq,/ibex/project/c2211/filtered_reads/combined/FS_1_filt_R2.fq
/ibex/project/c2211/filtered_reads/combined/FS_2_filt_R1.fq,/ibex/project/c2211/filtered_reads/combined/FS_2_filt_R2.fq
/ibex/project/c2211/filtered_reads/combined/FS_3_filt_R1.fq,/ibex/project/c2211/filtered_reads/combined/FS_3_filt_R2.fq
/ibex/project/c2211/filtered_reads/combined/K_1_filt_R1.fq,/ibex/project/c2211/filtered_reads/combined/K_1_filt_R2.fq
/ibex/project/c2211/filtered_reads/combined/K_2_filt_R1.fq,/ibex/project/c2211/filtered_reads/combined/K_2_filt_R2.fq
/ibex/project/c2211/filtered_reads/combined/K_3_filt_R1.fq,/ibex/project/c2211/filtered_reads/combined/K_3_filt_R2.fq
/ibex/project/c2211/filtered_reads/combined/Maj_1_filt_R1.fq,/ibex/project/c2211/filtered_reads/combined/Maj_1_filt_R2.fq
/ibex/project/c2211/filtered_reads/combined/Maj_2_filt_R1.fq,/ibex/project/c2211/filtered_reads/combined/Maj_2_filt_R2.fq
