### ISSUE TITLE
All cells of sheets of METABOLIC result table show absent/none

### ISSUE THREAD

**Issue by talam-biotech** [AnantharamanLab/METABOLIC#149]
**Describe the bug**
I ran Metabolic-G.pl on a number of genomes. With regard to output, all cells of sheets of METABOLIC result table show absent/none

Of note, the command seem to run normally, howerever the command printed:
readline() on closed filehandle _IN at METABOLIC-G.pl line 1236

<img width="1286" alt="image" src="https://github.com/AnantharamanLab/METABOLIC/assets/108459413/ef5dbc7f-885c-4182-938d-42f980c6244f">

**Comment by ChaoLab** [comment]
Hi,
Line 1236 corresponds to reading gene sequences
It seems that your gene files are missing.
Can you check your gene files in the genome-storing directory?

**Comment by talam-biotech** [comment]
Thank you for your timely reply. I think there maybe of been an issue with other files being present in the directory. Non-genome assembly files. It seems to be running normally now. Thank you for your help.

**Comment by ChaoLab** [comment]
Many thanks! I added more noticing information in my GitHub software usage page
