### ISSUE TITLE
Perl error

### ISSUE THREAD

**Issue by Thexiyang** [AnantharamanLab/METABOLIC#15]
Thanks for the nice tool. I keep getting the message like this: Use of uninitialized value $head_old in concatenation (.) or string at METABOLIC-G.pl line 1101, <_IN> line 515785. I used the command exactly as what shown in the help message. What could be the reason for this? How can I solve it? Thanks！

**Comment by ChaoLab** [comment]
Hi, Thexiyang, 
Many thanks for your interest in our software.
From the error report, I guess that it might result from your input files. For example, the dos/unix format, the last line in each genome fasta file, and so on. Can you check the inputs, or can you first use a small portion of your input files as a test?

Best regards!
