### ISSUE TITLE
GTDB version

### ISSUE THREAD

**Issue by CynthiaChibani** [AnantharamanLab/METABOLIC#150]
Would you mind specifying which GTDB release is compatible to run with METABOLIC-C??

EXCEPTION: FileNotFoundError
  MESSAGE: [Errno 2] No such file or directory: '~/GTDB/markers/pfam/individual_hmms/PF00380.14.hmm'

Thank you in advance.

**Comment by CynthiaChibani** [comment]
Hey there, I tried with R214 and gtdbk v.1.4 (or 1.9) it did not work. I updated gtdbtk v2.3.0 and tried with R207_v2 seems to be working. I do get the mentioned MW score_result and the All_gene_collections_transcript_coverage.txt. I get the coverage value of each function per genome, however, I get an empty column with the header "Taxonomic Group". I do have the information separately and can absolutely merge them however I am wondering what is the output expected from this analysis as I did not notice an example in the install repo. Would you mind referring to the template output if it exists? 
And the nice figure was generated separately and not part of running METABOLIC-C? 
Thank you in advance

**Comment by ChaoLab** [comment]
In the gtdbtk result dir, did you find proper results named `gtdbtk.ar53.summary.tsv` and `gtdbtk.bac120.summary.tsv`, respectively?
Can you send me the MW score result with an empty column with the header "Taxonomic Group"?

**Comment by CynthiaChibani** [comment]
[MW-score_result.txt](https://github.com/AnantharamanLab/METABOLIC/files/11685567/MW-score_result.txt)
[MW-score_result_table_input.txt](https://github.com/AnantharamanLab/METABOLIC/files/11685568/MW-score_result_table_input.txt)
Absolutely, here goes. thank you

**Comment by ChaoLab** [comment]
Hi,
I saw one of your genome stem name is like "BGR_140605_bin.1.strict".
It is suggested that the stem name only contains alphanumeric characters and underscores. I am not sure whether the dots are the problem, but it might be. Can you change it to "BGR_140605_bin_1_strict" can run again?

**Comment by CynthiaChibani** [comment]
Hey there, I get the same empty column after I change the . to _ in all input files.
I would appreciate any additional input you might have.
Thank you again

**Comment by ChaoLab** [comment]
Can you try to reinstall METABOLIC scripts and conda environments?

**Comment by CynthiaChibani** [comment]
apologies it is taking a bit longer than expected but I am on it and will get back to you ASAP.
