### ISSUE TITLE
Error in the instructions: All_Module_KO_ids.txt

### ISSUE THREAD

**Issue by michoug** [AnantharamanLab/METABOLIC#16]
Hi,
There is an error in the instructions to install:
the command: `mv All_Module_KO_ids.txt profiles` fails because you are in the `kofam_database` folder as the file is in the root folder.
It should be `mv ../All_Module_KO_ids.txt profile`
Best
Greg

**Comment by patriciatran** [comment]
Thanks again for another helpful comment! I've fixed this just now.
