### ISSUE TITLE
Possibly wrong link for MEROPS in run_to-setup.sh

### ISSUE THREAD

**Issue by CristinaMoraru** [AnantharamanLab/METABOLIC#169]
Hi there

I've followed the "Quick installation" instructions for METABOLIC_v4.0 and then I ran "bash run_to_setup.sh". 
It worked fine, untill it  got stuck when downloading MEROPS, from ftp://ftp.ebi.ac.uk/pub/databases/merops/current_release/pepunit.lib . It kept trying, but without success.

I've stopped the  run_to_setup.sh script and then I downloaded the pepunit.lib manually, from here: 
https://ftp.ebi.ac.uk/pub/databases/merops/current_release/pepunit.lib (bassically the same link as above, just https instead of ftp)

It worked fine, so maybe you want to change the link in the run_to_setup.sh script

Now I'm running the last steps in run_to_setup.sh script manually.

cheers

**Comment by patriciatran** [comment]
Thanks, I fixed it in this commit: 6f5abce6c74802df500a97e00e4ee2f76cfb249a
