### ISSUE TITLE
Should the arrow of Step8: Nitrite ammonification start from nitrate or nitrite?

### ISSUE THREAD

**Issue by huizhen-yan** [AnantharamanLab/METABOLIC#170]
Hi,
I noticed that in your article (Zhou2022-Microbiome, or Tran2021-ISMEJ), the arrow for step 8 starts from nitrate, while the arrow in the metabolic output result starts from nitrite. 

Is there something I overlooked about the nitrogen cycle causing the difference? Could it be a minor error? This is really confusing me.

Dissimilatory nitrate reduction to ammonium (DNRA), also known as nitrate/nitrite ammonification, consists of two steps: nitrate reduction and nitrite reduction to ammonia. According to METABOLIC_result_each_spreadsheet/METABOLIC_result_worksheet2.tsv, nitrite ammonification in the nitrogen cycling that METABOLIC tool focuses on refers to "nitrite reduction to ammonia", including nrfADH||nirBD genes. Therefore, I think step 8 should start with nitrite.

I want to know if METABOLIC software considers napAB||narGH genes (shared with nitrate reduction) when evaluating a genome's ability to perform step 8: nitrite ammonification (-module-cutoff default: 0.75).

Thank you so much.

**Comment by patriciatran** [comment]
Hi,
It's been fixed in the METABOLIC code in 2022. 
Step 8 starts at nitrite:
See: https://github.com/AnantharamanLab/METABOLIC/commit/2b28e5fb21de687734eb170644aa5c5abe492e0f
