### ISSUE TITLE
How to get access to test google drive files?

### ISSUE THREAD

**Issue by Henryranger888** [AnantharamanLab/METABOLIC#172]
I have tried the installation guide on the wiki page, but failed with the final step through gdown to get the test files.
The result in the terminal was like :
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1JQJpw_elM4IyGo_BIfioy8XnmqgoN-Iw 

I have noticed new link has been provided in the previous issue. However its still can't work in my current situation. 
Thanks for the help.

**Comment by diogoburgos** [comment]
I'm having this problem too.

**Comment by patriciatran** [comment]
See my responses in issue #176
