### ISSUE TITLE
Access to test filés in google drive 

### ISSUE THREAD

**Issue by diogoburgos** [AnantharamanLab/METABOLIC#176]
I don't have access to the test files in google drive by the link in step 8 of the instalation process. How can I get it?

**Comment by patriciatran** [comment]
I’ll check to see if I have a copy somewhere this week. The original google drive link is from my colleague’s account.

**Comment by patriciatran** [comment]
Hi, 

while the script https://github.com/AnantharamanLab/METABOLIC/blob/master/run_to_setup.sh was updated, the manual installation instructions in the wiki were not. 

I updated them in this update: [2d6d087](https://github.com/AnantharamanLab/METABOLIC/wiki/Installation/2d6d0876cd0f56d9491c210081860c4732d8b9ab)

Try:
```
wget -c https://figshare.com/ndownloader/files/43500597 -O METABOLIC_test_files.tgz
tar zxvf METABOLIC_test_files.tgz
rm *.tgz
```
