### ISSUE TITLE
Can metabolic used for annotation of virus genome?

### ISSUE THREAD

**Issue by xjhzjucas** [AnantharamanLab/METABOLIC#178]
Hi developer,
I am curious about whether this brilliant tool used for virus genome annotation to figure out some viral metabolic feature?

**Comment by patriciatran** [comment]
No, this tool was built for bacterial and archeal genomes. 
It does not use any viral databases for annotations and therefore is not suited for that.

**Comment by xjhzjucas** [comment]
> No, this tool was built for bacterial and archeal genomes. It does not use any viral databases for annotations and therefore is not suited for that.

OK, thank you for your help!
