### ISSUE TITLE
Error in METABOLIC_result.xlsx

### ISSUE THREAD

**Issue by michoug** [AnantharamanLab/METABOLIC#19]
Hi,
I ran the 5_genomes test and when I open the file `METABOLIC_result.xlsx`, first it was "repaired" by excel and the log told me that `Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.`
Secondly, 4 of the 5 genomes don't have any genes while the 5th genome had some gene present but the hits were from several genomes, i.e. `CP002100.1_595,CP002100.1_595,CP031156.1_1669,CP031156.1_1669` for `K00817.hmm`

[METABOLIC_result.xlsx](https://github.com/AnantharamanLab/METABOLIC/files/4622100/METABOLIC_result.xlsx)

**Comment by ChaoLab** [comment]
Hi, Michoug,
There is a problem with our scripts.  I have changed accordingly.
Can you have a try with the new METABOLIC-G script?

Best regards!

**Comment by michoug** [comment]
Thanks, it fixed the issue
