### ISSUE TITLE
Wrong results in METABOLIC_result.xlsx

### ISSUE THREAD

**Issue by PandengWang** [AnantharamanLab/METABOLIC#20]
Thank you so much for developing this extremely useful tool.
I updated this tool to the latest version one week ago. After I run it with my genomes, the contents in METABOLIC_result.xlsx are as follows:

Category | Function | Gene   abbreviation | Gene name | Hmm file | Corresponding KO | Reaction | Substrate | Product | Gn0001 Hmm   presence | Gn0001 Hit   numbers | Gn0001 Hits | Gn0002 Hmm   presence | Gn0002 Hit   numbers | Gn0002 Hits
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Thermophilic   specific | Thermophilic specific | rgy | reverse gyrase | TIGR01054.hmm | K03170 | Thermophilic specific | N/A | N/A | Absent | 0 | None | Absent | 0 | None
Amino acid   utilization | 4-aminobutyrate   aminotransferase and related aminotransferases | 4-aminobutyrate   aminotransferase and related aminotransferases | 4-aminobutyrate   aminotransferase and related aminotransferases | K00823.hmm,   K07250.hmm, K13524.hmm, K14268.hmm, K03918.hmm | K00823, K07250,   K13524, K14268, K03918 | 4-aminobutanoate +   2-oxoglutarate = succinate semialdehyde + L-glutamate [RN:R01648] | 4-aminobutanoate;   2-oxoglutarate | succinate   semialdehyde; L-glutamate | Absent | 0 | None | Absent | 0 | None
Amino acid   utilization | Aminotransferase   class I and II | aminotransferase   class I and II | aminotransferase   class I and II | K05825.hmm | K05825 | L-2-aminoadipate +   2-oxoglutarate = 2-oxoadipate + L-glutamate [RN:R01939] | L-2-aminoadipate;   2-oxoglutarate | 2-oxoadipate;   L-glutamate | Present | 1 | None | Present | 2 | None
Amino acid   utilization | Phosphoserine   aminotransferase | phosphoserine   aminotransferase | phosphoserine   aminotransferase | K00831.hmm | K00831 | O-phospho-L-serine +   2-oxoglutarate = 3-phosphooxypyruvate + L-glutamate [RN:R04173];   4-phosphooxy-L-threonine + 2-oxoglutarate =   (3R)-3-hydroxy-2-oxo-4-phosphooxybutanoate + L-glutamate [RN:R05085] | O-phospho-L-serine;   2-oxoglutarate; 4-phosphooxy-L-threonine | 3-phosphooxypyruvate;   L-glutamate; (3R)-3-hydroxy-2-oxo-4-phosphooxybutanoate | Present | 1 | None | Present | 1 | None
Amino acid   utilization | Ornithine/acetylornithine   aminotransferase | ornithine/acetylornithine   aminotransferase | ornithine/acetylornithine   aminotransferase | K00819.hmm,   K00821.hmm, K05830.hmm, K00840.hmm | K00819, K00821,   K05830, K00840 | L-ornithine + a 2-oxo   carboxylate = L-glutamate 5-semialdehyde + an L-amino acid [RN:R01343] | L-ornithine; 2-oxo   carboxylate | L-glutamate   5-semialdehyde; L-amino acid | Absent | 0 | None | Absent | 0 | None
Amino acid   utilization | Branched-chain amino   acid aminotransferase/4-amino-4-deoxychorismate lyase | branched-chain amino   acid aminotransferase/4-amino-4-deoxychorismate lyase | branched-chain amino   acid aminotransferase/4-amino-4-deoxychorismate lyase | K00826.hmm,   K02619.hmm, K03342.hmm | K00826, K02619,   K03342 | L-leucine +   2-oxoglutarate = 4-methyl-2-oxopentanoate + L-glutamate [RN:R01090] | L-leucine;   2-oxoglutarate | 4-methyl-2-oxopentanoate;   L-glutamate | Absent | 0 | None | Absent | 0 | None
Amino acid   utilization | Aspartate/tyrosine/aromatic   aminotransferase | aspartate/tyrosine/aromatic   aminotransferase | aspartate/tyrosine/aromatic   aminotransferase | K00812.hmm,   K00813.hmm, K11358.hmm, K00832.hmm | K00812, K00813,   K11358, K00832 | L-aspartate +   2-oxoglutarate = oxaloacetate + L-glutamate [RN:R00355] | L-aspartate;   2-oxoglutarate | oxaloacetate;   L-glutamate | Absent | 0 | None | Absent | 0 | None
Amino acid   utilization | Histidinol-phosphate/aromatic   aminotransferase | histidinol-phosphate/aromatic   aminotransferase | histidinol-phosphate/aromatic   aminotransferase | K00817.hmm | K00817 | L-histidinol   phosphate + 2-oxoglutarate = 3-(imidazol-4-yl)-2-oxopropyl phosphate +   L-glutamate [RN:R03243] | L-histidinol   phosphate; 2-oxoglutarate | 3-(imidazol-4-yl)-2-oxopropyl   phosphate; L-glutamate | Present | 1 | None | Present | 1 | None

**Gn0001 Hits** and **Gn0001 Hmm presence** didn't match each other.

**Comment by ChaoLab** [comment]
Hi, Wang,
Thanks very much for your interest in our software. We noticed that this problem is caused by our carelessness in the last version update. We are working on solving this problem and other issues. The new version will be provided in the coming few days!

**Comment by Ahmed-Shibl** [comment]
Thanks for this tool! I gave it a go and got the METABOLIC_result.xlsx file and was also wondering about the results. First, I want to mention that my input was three bacterial genomes and I used `perl METABOLIC-G.pl` 

Is it natural that each GenomeXX.Hmm.presence column says **absent** for all rows but the total.Hmm.presence shows **present** for some?
![Screen Shot 2020-09-08 at 11 48 51 AM](https://user-images.githubusercontent.com/39734354/92448176-49607480-f1c9-11ea-8b08-6669e2752847.png)

Similarly, the nutrient cycling diagrams have no red arrows in any of the GenomeXX.draw PDFs but shows some red arrows in the total.draw PDF output...

Thanks in advance!

**Comment by patriciatran** [comment]
Hi @Ahmed-Shibl ,
Thank you for letting us know. We can definitely look into it and why you are getting these types of results. Would you like to send your .fna files for your genomes so that we can replicate your results? If you would like, you can send them by email to : ptran5 [at] wisc [dot] edu . We won't use the genomes for anything else than trying to resolve this issue of course.
Patricia

**Comment by ChaoLab** [comment]
> Thanks for this tool! I gave it a go and got the METABOLIC_result.xlsx file and was also wondering about the results. First, I want to mention that my input was three bacterial genomes and I used `perl METABOLIC-G.pl`
> 
> Is it natural that each GenomeXX.Hmm.presence column says **absent** for all rows but the total.Hmm.presence shows **present** for some?
> ![Screen Shot 2020-09-08 at 11 48 51 AM](https://user-images.githubusercontent.com/39734354/92448176-49607480-f1c9-11ea-8b08-6669e2752847.png)
> 
> Similarly, the nutrient cycling diagrams have no red arrows in any of the GenomeXX.draw PDFs but shows some red arrows in the total.draw PDF output...
> 
> It might also be worth mentioning that despite the script ran from start to end, I did get these errors repeatedly:
> 
> ```
> readline() on closed filehandle _IN at METABOLIC-G.pl line 1308.
> Use of uninitialized value $seq in pattern match (m//) at METABOLIC-G.pl line 356.
> ```
> 
> and
> 
> ```
> Use of uninitialized value $head_old in concatenation (.) or string at METABOLIC-G.pl line 1154, <_IN> line 51387.
> Use of uninitialized value $head_old in concatenation (.) or string at METABOLIC-G.pl line 1154, <_IN> line 51389.
> Use of uninitialized value $head_old in concatenation (.) or string at METABOLIC-G.pl line 1154, <_IN> line 51391.
> Use of uninitialized value $head_old in concatenation (.) or string at METABOLIC-G.pl line 1154, <_IN> line 51393.
> Use of uninitialized value $head_old in concatenation (.) or string at METABOLIC-G.pl line 1154, <_IN> line 51395.
> Use of uninitialized value $head_old in concatenation (.) or string at METABOLIC-G.pl line 1154, <_IN> line 51397.
> Use of uninitialized value $head_old in concatenation (.) or string at METABOLIC-G.pl line 1154, <_IN> line 51399.
> ```
> 
> Thanks in advance! @patriciatran @ChaoLab

Hi Ahmed-Shibl，
The "total.faa" is actually an intermediate file in the genome folder, and it should be deleted after the hmmsearch step was done. So there should be not a "total.Hmm.presence" and hits in your final resulted excel file.  I think this would be the reason for your other problems.  Did you run two times in a short time? or did you not fully cancel your first run before you started a second run?

Best!

**Comment by ChaoLab** [comment]
Hi Ahmed-Shibl, 
we have run the genome from you, discovered that it is because of our previous settings to read the faa file. We have updated both METABOLIC-G and -C  scripts. You may have a try again. 
Many thanks for your information to help us improve the software.

Best!
