### ISSUE TITLE
Error when ggplot was used to plot

### ISSUE THREAD

**Issue by Bro-Miao** [AnantharamanLab/METABOLIC#28]
When I used METABOLIC-C.pl I got this error: Error: Must request at least one colour from a hue palette. And the CommunityPlot.PDF was empty.
The log file was attached below.
[nohup.txt](https://github.com/AnantharamanLab/METABOLIC/files/5779742/nohup.txt)
![1609997292(1)](https://user-images.githubusercontent.com/72309656/103854755-35337200-50ec-11eb-8070-d3ae6479e029.jpg)

I don't know how to deal with this. Could you please help me with this?

**Comment by patriciatran** [comment]
Hi @Bro-Miao, the R script that gives you this error is this one[ this one. ](https://github.com/AnantharamanLab/METABOLIC/blob/0f1402e3869345ac0f69cfe06983ec2e4154ada5/draw_metabolic_energy_flow.R). I think infer.label is deprecated in the [ggalluvial packages in version 0.12.3](http://corybrunson.github.io/ggalluvial/reference/stat_stratum.html). I'm going to work today on fixing this bug in the R script and give you an update. 
Thanks for letting us know!

**Comment by Bro-Miao** [comment]
Thank you very much. I have changed the ggalluvial version ang it works now.
