### ISSUE TITLE
Question about GTDBtk

### ISSUE THREAD

**Issue by susheelbhanu** [AnantharamanLab/METABOLIC#29]
Hi, 

Firstly, thanks for a great tool. I have a question regarding setting the path to the `GTDBtk` database. I already have the latest version, and was wondering if there's a flag in the `METABOLIC-G.pl` or the `-C` scripts for specifying the path to the directory?

Thank you,
Susheel

**Comment by ChaoLab** [comment]
Hi,
METABOLIC-C will use gtdbtk. I am not sure whether you mean the path of the gtdbtk database or the output folder of gtdbtk run.

**Comment by susheelbhanu** [comment]
Thank you. I'm referring to the `path` of the gtdbtk database. Is there a way to specify it along with the run command?

**Comment by ChaoLab** [comment]
I breifly looked at gtdbtk, found that it is not easy to set a new path for gtdbtk database instead of the default. We use gtdbtk by using its default settings. Maybe it will be easier to just re-install your gtdbtk.

**Comment by susheelbhanu** [comment]
Hey @ChaoLab, 

I'm sorry I wasn't clearer earlier. According to the installation instructions, one can do the following:
```
Set the GTDBTK_DATA_PATH environment variable in the file:
$PATH/metabolic/etc/conda/activate.d
``` 

I was wondering, instead of doing the above whether one could do something like the below:
```
perl METABOLIC-C.pl <input> <output> --database PATH/TO/GTDBtk-database
```
I'm guessing you don't have that functionality - please let me know if otherwise. 

Thank you!

**Comment by ChaoLab** [comment]
It seemes one can set gtdbtk database path during installation. While, once after installation, gtdbtk database path is fixed, I could not find an option from gtdbtk to change the path.

**Comment by susheelbhanu** [comment]
Fair enough - thank you!
