### ISSUE TITLE
Error in draw_biogeochemical_cycles.R

### ISSUE THREAD

**Issue by michoug** [AnantharamanLab/METABOLIC#3]
Hi,
there is a confusion in the graph about anammox and nitrite ammonification, the data are inverted :

The input 

Total.R_input.txt

```
N-S-07:Nitrous oxide reduction	15	0.0404908627697313
N-S-08:Nitrite ammonification	28	0.196098546607314
N-S-09:Anammox	0	0
O-S-01:Metal reduction	1	0
```

and in the script
draw_biogeochemical_cycles.R

  ```
textplain(mid = c(0.55, 0.65), 
            lab = c("Step9: Anammox",
                    paste("Genomes:",input.total$Nb.Genome[17]),
                    paste("Coverage:",input.total$Genome.Coverage.Percentages.Round[17],"%"))) 
  textplain(mid = c(0.47, 0.35), 
            lab = c("Step8: Nitrite ammonification",
                    paste("Genomes:",input.total$Nb.Genome[18]),
                    paste("Coverage:",input.total$Genome.Coverage.Percentages.Round[18],"%")))
```

See the attached figure

[draw_nitrogen_cycle_total.pdf](https://github.com/AnantharamanLab/METABOLIC/files/3630109/draw_nitrogen_cycle_total.pdf)

Best
Greg

**Comment by patriciatran** [comment]
I just changed the index numbers referring those reactions with commit https://github.com/AnantharamanLab/METABOLIC/commit/e7e926bf01b87540ea8c79875e5a7cff60c91c9a. If you have time you can run the R script again and let me know if that resolved your issue. If so I will close this issue. Thank you for letting us know.

**Comment by michoug** [comment]
Hi yes it worked
Greg
