### ISSUE TITLE
problem with dbCAN2

### ISSUE THREAD

**Issue by jarojasva** [AnantharamanLab/METABOLIC#30]
Hello,

I've had a problem with the program. I'm trying to use it with 4 diferent genomes, but at certain point, there were the next errors:

[2021-02-15 11:12:17] Searching CAZymes by dbCAN2...
Error:
Error:
Error:
Error: Failed to open binary auxfiles for /mnt/c/Users/AsusLap/Documents/Otros/Apps/METABOLIC-master/dbCAN2/dbCAN-fam-HMMs.txt: use hmmpress first
Failed to open binary auxfiles for /mnt/c/Users/AsusLap/Documents/Otros/Apps/METABOLIC-master/dbCAN2/dbCAN-fam-HMMs.txt: use hmmpress first
Failed to open binary auxfiles for /mnt/c/Users/AsusLap/Documents/Otros/Apps/METABOLIC-master/dbCAN2/dbCAN-fam-HMMs.txt: use hmmpress first
Failed to open binary auxfiles for /mnt/c/Users/AsusLap/Documents/Otros/Apps/METABOLIC-master/dbCAN2/dbCAN-fam-HMMs.txt: use hmmpress first

cat: /mnt/c/Users/AsusLap/Documents/UNAM/Semestre_5/MetabolicProject/Metabolic_Results/intermediate_files/dbCAN2_Files/369_Pseudomonas_A5.feature_protein.dbCAN2.out.dm: No such file or directorycat:
cat: /mnt/c/Users/AsusLap/Documents/UNAM/Semestre_5/MetabolicProject/Metabolic_Results/intermediate_files/dbCAN2_Files/183_Paenarthrobacter_A5.feature_protein.dbCAN2.out.dmcat: /mnt/c/Users/AsusLap/Documents/UNAM/Semestre_5/MetabolicProject/Metabolic_Results/intermediate_files/dbCAN2_Files/A1_Pseudomonas_A5.feature_protein.dbCAN2.out.dm: No such file or directory/mnt/c/Users/AsusLap/Documents/UNAM/Semestre_5/MetabolicProject/Metabolic_Results/intermediate_files/dbCAN2_Files/181_Alcanivorax_A5.feature_protein.dbCAN2.out.dm: No such file or directory
: No such file or directory
[2021-02-15 11:12:19] dbCAN2 searching is done
[2021-02-15 11:12:19] Searching MEROPS peptidase...
[2021-02-15 11:17:11] MEROPS peptidase searching is done
sh: 1: Rscript: Permission denied
mv: cannot stat 'METABOLIC_result.xlsx': No such file or directory
[2021-02-15 11:17:11] METABOLIC table has been generated
[2021-02-15 11:17:11] Drawing element cycling diagrams...
sh: 1: Rscript: Permission denied
mv: cannot stat '/mnt/c/Users/AsusLap/Documents/UNAM/Semestre_5/MetabolicProject/Metabolic_Results/Output/draw_biogeochem_cycles': No such file or directory
rm: cannot remove '/mnt/c/Users/AsusLap/Documents/UNAM/Semestre_5/MetabolicProject/Metabolic_Results/Output': No such file or directory
[2021-02-15 11:17:12] Drawing element cycling diagrams finished

So there were no diagrams or other results generated. What should I do?

**Comment by ChaoLab** [comment]
Hi,
It seems that your dbCAN2 is not set up well. From “use hmmpress first”, I guess, maybe, some hmm profiles have not been pressed. Maybe this could be the problem.

All my best!

**Comment by patriciatran** [comment]
closing because we figured it out by email. The solution is to use hmmpress which is found in the set up .sh script.

**Comment by fatimalihau** [comment]
Hi, and thank you for the awesome software. I am having the same issue with hmmpress Error. Could you elaborate a bit more on the solution?
