### ISSUE TITLE
RuBisCo hmm output parsing

### ISSUE THREAD

**Issue by strejcem** [AnantharamanLab/METABOLIC#42]
Hello,
I'd like to report strange behavior of parsing hmm outputs of rubisco. There are hits in _rubisco_form_III.hmm.total.hmmsearch_result.txt_ (score threshold = 450). However, if I check the _HMMHitNum_ spreadsheet the RuBisCo Form III is absent in all MAGs. There are also hits in _K01601.hmm.total.hmmsearch_result.txt_ (threshold = 409.67 score) and the _KEGGModuleStepHit_ shows some irregular results; depending on the module it shows absent/present although the module step should be the same protein/ko. See picture below:
![rbcl](https://user-images.githubusercontent.com/12595371/113760498-96cca200-9716-11eb-91a1-0f2524657a02.png)

I am not sure if it is really a bug as I don't precisely understand how the noise and trusted cutoffs works as described in the manuscript. Is there any filtering step after the hmm search using defined score thresholds? Anyway, BLASTP shows the closest proteins are RuBisCo form III with cca 55% identity against RefSeq and 90% against NR.

METABOLIC v4.0

Protein in question:
> \>MAG03_10_4
MVHEKYEDFVELSYKPSKKELLCSFYVEPAAGESIKRAAGAVASESSVGTWTSVPGLHLKHVMKIAATCYEINGNWIKIAYPVENFEPGSLPQIFSSIAGNVFGMKAVRNLRLHDVEWPLSLKRSFPGPQFGIDGIRKILKVQGRPITASVPKPKIGMTAEEHAQIGYKIWTGGFDLLKDDENLTSQKFDRFEDRVKHSMRMREKAEKETGERKACLLNITAPFQEMVKRAKLVSDYGNEYVMVDMLTIGWSALQGIREVCEELKLALYAHRAFHAAFTRNRRHGMSMLVVAESARLAGVDNVHIGTVVGKLESPKEEVLAIHERMQKQKIESDSRQHLFGEDWGSMKKVMSTSSGGLHPGLIPKIIKMLGRDIAIQVGGGVHGHPDGSKAGATAVMQAIDAALKEIPLREYAKTHKELKAALVQWGYLMPR

**Comment by ChaoLab** [comment]
Hi, I suggest to follow the result of "rubisco_form_III.hmm.total.hmmsearch_result.txt". There are discrepancies between our custom HMM result and Kofam HMM result, and normally we follow the former one. Novel proteins/unconventional proteins will introduce some problems, some time different annotating methods will give different results. I think it will be good to build phylogenetic trees to further ascertain some proteins, and you could also make some changes to the final table according to the solid annotation result.

**Comment by strejcem** [comment]
Thanks for quick reply. Just to be sure, is it OK to have hits in custom _hmmseach_result.txt_ but not _present_ in the HMMHitNum table?

**Comment by ChaoLab** [comment]
No, all results in *hmmseach_result.txt should be the same with those in HMMHitNum table

**Comment by strejcem** [comment]
If anyone in the future have the same issues I solved the hmmsearch hits vs absence in HMMMHitNum. There is a motif filter for Form I and III of RuBisCo when searched against the custom hmm (not KEGG hmm). Be mindful if you are working with uncharacterized metagenomes. As suggested by @ChaoLab, further analysis is required. 

Potentially a code enhancement would be to export sequences that were detected by hmm search but excluded by motif filtering. 

There is still the issue as shown in attached picture in the first post. The same steps of overlapping modules are present/absent depending on the module.
