### ISSUE TITLE
Question on MN-score_results.txt

### ISSUE THREAD

**Issue by mherold1** [AnantharamanLab/METABOLIC#48]
Hello,

In the output file MN-score_results.txt I have one more column than phyla, i.e., one unlabelled column. Is this the percentage that is from MAGs that could not be assigned taxonomically?
![image](https://user-images.githubusercontent.com/10416078/121529000-4581ad00-c9fc-11eb-9df7-32a785b56359.png)

Thanks for your help.

**Comment by ChaoLab** [comment]
Hi, do you mean the first num-containing column (2nd column)? That's "MN-score for each function"
