### ISSUE TITLE
How do I explain the percentage of coverage

### ISSUE THREAD

**Issue by Qicheng-Xu** [AnantharamanLab/METABOLIC#54]
I thought the coverage in files, for example draw_carbon_cycle_total.pdf, was the percentage of MAGs harboring the specific functions in the whole community, i.e., (sequences mapped to MAGs)/(total sequences in the metagenomic datasets). However, I got a coverage value of 100%, that means, the MAGs I provided to METABOLIC accounted for 100% of the whole community. This is impossible.
So, could you explain that what is the coverage referred to? 
Thank you!
Bests,
Qicheng
![image](https://user-images.githubusercontent.com/57284391/136651629-f9a4d991-1619-44c8-ba5c-93d2fa2b7eac.png)

**Comment by ChaoLab** [comment]
The coverage percentage means the fraction of coverage values of genomes that have the pathway step over the coverage values of all the genomes. If all the input genomes (7 genomes) have Step1, then the coverage percentage should be 100%

**Comment by Qicheng-Xu** [comment]
OK, you mean the coverage= the relative abundance of MAGs that harboring the functions / the relative abundance of all the input MAGs, right?
