### ISSUE TITLE
Use the results of METABOLIC-G.pl to run METABOLIC-C.pl

### ISSUE THREAD

**Issue by maocheng2020** [AnantharamanLab/METABOLIC#56]
Hello, I have successfully run METABOLIC-G.pl, how should I set the command to use the result of METABOLIC-G.pl to run METABOLIC-C.pl, it seems that a large part of them are repeated, which is helpful to save time, can you achieve it, thank you very much!

**Comment by ChaoLab** [comment]
Hi @maocheng2020  There is no a fast and easy way to transfer the result of METABOLIC-G to METABOLIC-C. Normally, METABOLIC-C will cost much more time in reads mapping and GTDB-Tk running than in the hmmsearch step. I suggest to run METABOLIC-C directly; METABOLIC-C result will be more comprehensive than that of METABOLIC-G.

**Comment by maocheng2020** [comment]
Thank you@ChaoLab . I can successfully run G, but when I run G, I find the following error:

[2021-11-26 04:16:58] MEROPS peptidase searching is done
[2021-11-26 04:17:02] METABOLIC table has been generated
[2021-11-26 04:17:02] Drawing element cycling diagrams...
stat: Bad file descriptor
Warning: Could not open read file "/root/data2/2018/june/A1_clean_2.fastq^M" for reading; skipping...
Error: No input read files were valid
(ERR): bowtie2-align exited with value 1
stat: Bad file descriptor
Warning: Could not open read file "/root/data2/2018/june/A2_clean_2.fastq^M" for reading; skipping...
Error: No input read files were valid
(ERR): bowtie2-align exited with value 1
[E::hts_open_format] Failed to open file metabolic_out6C/All_gene_collections_mapped.1.sorted.bam
samtools index: failed to open "metabolic_out6C/All_gene_collections_mapped.1.sorted.bam": No such file or directory
rm: cannot remove 'metabolic_out6C/All_gene_collections_mapped.1.sam': No such file or directory
stat: Bad file descriptor
Warning: Could not open read file "/root/data2/2018/june/A3_clean_2.fastq^M" for reading; skipping...
Error: No input read files were valid
(ERR): bowtie2-align exited with value 1

When I checked the absolute path, I didn't find any problems, which was frustrating .

/root/data2/2018/june/A1_clean_1.fastq,/root/data2/2018/june/A1_clean_2.fastq
/root/data2/2018/june/A2_clean_1.fastq,/root/data2/2018/june/A2_clean_2.fastq
/root/data2/2018/june/A3_clean_1.fastq,/root/data2/2018/june/A3_clean_2.fastq

Will this error only be a path problem？ I can get to this folder from anywhere via cd /root/data2/2018/june/

**Comment by maocheng2020** [comment]
> Hi @maocheng2020 There is no a fast and easy way to transfer the result of METABOLIC-G to METABOLIC-C. Normally, METABOLIC-C will cost much more time in reads mapping and GTDB-Tk running than in the hmmsearch step. I suggest to run METABOLIC-C directly; METABOLIC-C result will be more comprehensive than that of METABOLIC-G.

Thank you@ChaoLab . I can successfully run G, but when I run G, I find the following error:

[2021-11-26 04:16:58] MEROPS peptidase searching is done
[2021-11-26 04:17:02] METABOLIC table has been generated
[2021-11-26 04:17:02] Drawing element cycling diagrams...
stat: Bad file descriptor
Warning: Could not open read file "/root/data2/2018/june/A1_clean_2.fastq^M" for reading; skipping...
Error: No input read files were valid
(ERR): bowtie2-align exited with value 1
stat: Bad file descriptor
Warning: Could not open read file "/root/data2/2018/june/A2_clean_2.fastq^M" for reading; skipping...
Error: No input read files were valid
(ERR): bowtie2-align exited with value 1
[E::hts_open_format] Failed to open file metabolic_out6C/All_gene_collections_mapped.1.sorted.bam
samtools index: failed to open "metabolic_out6C/All_gene_collections_mapped.1.sorted.bam": No such file or directory
rm: cannot remove 'metabolic_out6C/All_gene_collections_mapped.1.sam': No such file or directory
stat: Bad file descriptor
Warning: Could not open read file "/root/data2/2018/june/A3_clean_2.fastq^M" for reading; skipping...
Error: No input read files were valid
(ERR): bowtie2-align exited with value 1

When I checked the absolute path, I didn't find any problems, which was frustrating .

/root/data2/2018/june/A1_clean_1.fastq,/root/data2/2018/june/A1_clean_2.fastq
/root/data2/2018/june/A2_clean_1.fastq,/root/data2/2018/june/A2_clean_2.fastq
/root/data2/2018/june/A3_clean_1.fastq,/root/data2/2018/june/A3_clean_2.fastq

Will this error only be a path problem？ I can get to this folder from anywhere via cd /root/data2/2018/june/

**Comment by ChaoLab** [comment]
It seems that your reads input file is in a Windows format, you will need to use "dos2unix" to change it to Unix format

**Comment by maocheng2020** [comment]
> It seems that your reads input file is in a Windows format, you will need to use "dos2unix" to change it to Unix format

**The same problem occurs when I run the test data，**
perl METABOLIC-C.pl -in-gn METABOLIC_test_files/Guaymas_Basin_genome_files -r METABOLIC_test_files/Reads_address_6.txt -o METABOLIC_test_files/test6 -t 48

[2021-12-01 02:50:04] Drawing element cycling diagrams...
stat: Bad file descriptor
" for reading; skipping...ad file "/root/data4/data/mc/binning/bin_metabolic/METABOLIC/METABOLIC_test_files/METABOLIC_test_reads/SRR3577362_sub_2.fastq
Error: No input read files were valid
(ERR): bowtie2-align exited with value 1
[E::hts_open_format] Failed to open file METABOLIC_test_files/test7/All_gene_collections_mapped.1.sorted.bam
samtools index: failed to open "METABOLIC_test_files/test7/All_gene_collections_mapped.1.sorted.bam": No such file or directory
rm: cannot remove 'METABOLIC_test_files/test7/All_gene_collections_mapped.1.sam': No such file or directory
rm: cannot remove 'METABOLIC_test_files/test7/*.bam': No such file or directory
rm: cannot remove 'METABOLIC_test_files/test7/*.bai': No such file or directory
Loading required package: shape
[2021-12-01 02:50:23] Drawing element cycling diagrams finished

I don't know if this is a Perl problem?
