### ISSUE TITLE
perl script shebang line

### ISSUE THREAD

**Issue by nick-youngblut** [AnantharamanLab/METABOLIC#59]
The installation docs state:

>Note that one additional step is required: the shebang line of the two main scripts (METABOLIC-C.pl and METABOLIC-G.pl) should be edited to match the perl installation in your conda environment (ie: #! /path/to/conda/env/bin/perl)

Why not just use `#!/usr/bin/env perl`, which should use whichever perl executable in the user's PATH?

**Comment by ChaoLab** [comment]
@nick-youngblut  Many thanks for this suggestion! We changed the script and 'Note' info accordingly.

**Comment by nick-youngblut** [comment]
Great! Thanks for implementing the change so quickly!
