### ISSUE TITLE
metagenomics reads

### ISSUE THREAD

**Issue by clarelou0128** [AnantharamanLab/METABOLIC#6]
**Describe the bug**
do metagenomics reads have to be in unzipped format? can I run this using zipped reads?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ChaoLab** [comment]
Currently, you need to provide unzipped metagenomic reads.
