### ISSUE TITLE
Inserting both long and short read .fastq filepaths in -r txt file (from polished contig annotations)

### ISSUE THREAD

**Issue by mhyleung** [AnantharamanLab/METABOLIC#64]
Dear all

I have both Nanopore and Illumina reads for the same sample, and have performed assembly after some polishing works. Does METABOLIC support some sort of adjustments on read coverage analysis if we put both Illumina and Nanopore reads for a single METABOLIC-C run?

Thanks

Marcus

**Comment by ChaoLab** [comment]
Hi Marcus,
METABOLIC can not incorporate different reads now. You can probably generate a depth file by yourself by using both illumina and nanopore reads, and use the 2nd run script (https://github.com/AnantharamanLab/METABOLIC/wiki/METABOLIC-Usage#a-2nd-metabolic-c-run) to directly apply the depth file that you generated. 

The mapping reference "All_gene_collections.gene" is the concatenated gene file containing all input genomes (you can find them in the input genome folder).

Chao

**Comment by mhyleung** [comment]
Thanks Chao!
