### ISSUE TITLE
Is it possible to run the metagenomic assembled genomes with Metatranscriptomic?

### ISSUE THREAD

**Issue by XW-suron** [AnantharamanLab/METABOLIC#66]
Hi,

when I run the METABOLIC-C.pl with input files of metagenomic assembled genomes and Metatranscriptomic paired-end reads, it returns the following error:

"Drawing element cycling diagrams...
readline() on closed filehandle __IN at METABOLIC-C.pl line 1904.
Illegal division by zero at METABOLIC-C.pl line 1944."

Does it mean that it is not proper parameters used or not proper to run input files of metagenomic assembled genomes and Metatranscriptomic paired-end reads?

Any possible solutions for this?

Best

**Comment by ChaoLab** [comment]
It seems that your reads input file is not prepared well, METABOLIC did not properly intake these files
Please refer to this section: https://github.com/AnantharamanLab/METABOLIC/wiki/METABOLIC-Usage#all-required-and-optional-flags

**Comment by XW-suron** [comment]
Hi,

I use the following command line:
"perl METABOLIC-C.pl -in-gn path-to-my-bins -rt metaT -r metatranscriptome-reads/trans.txt -o trans_C27 -tax genus -t 100"

Actually, I have flagged the metaT...that is to say the METABOLIC-C.pl cannit intake the genomes (.fasta files made from metagenome reads) and Metatranscriptomic paired-end reads together?

Best

**Comment by XW-suron** [comment]
I found a mistake in preparing the intake file (extra space in the name of the TXT file). Now it finally runs the genomes (.fasta files made from metagenome reads) with Metatranscriptomic paired-end reads together...

Many thanks for your help.

Best
