### ISSUE TITLE
fasta file not enough input for Metabolic-g? Error as keep looking for a total.faa file.

### ISSUE THREAD

**Issue by Dwrgi** [AnantharamanLab/METABOLIC#67]
I have done a full install of METABOLIC on Ubuntu in VirtualBox and successfully run the test (sudo perl METABOLIC-G.pl -test true).

I then tried to run METABOLIC-G on a .fasta file containing 5 contigs from a single genome. Since the instructions say that this is the minimum requirements:
perl METABOLIC-G.pl -in-gn [path_to_folder_with_genome_files] -o [output_directory_to_be_created]

I ran the following (sudo perl METABOLIC-G.pl -in-gn Sporosarcina_1/ -o Sporosarcina_1_out), with the directory Sporosarcina_1 containing my .fasta file (Weds_5contigs.fasta). The run got off to a good start but then it started throwing up an error message ("Error: Failed to open sequence file Sporosarcina_1//total.faa for reading") that was repeated over and over until I killed the run.

I didn't think I would have to provide an .faa file?
Or is this indicative of an issue with the hmmsearch that wasn't an issue during the test run?

Thanks!

**Output:**
_________________________________
sara@VB-ubuntu:~/METABOLIC$ sudo perl METABOLIC-G.pl -in-gn Sporosarcina_1/ -o Sporosarcina_1_out
[2022-03-29 15:08:28] The Prodigal annotation is running...
[2022-03-29 15:10:47] The Prodigal annotation is finished
[2022-03-29 15:10:47] The hmmsearch is running with 20 cpu threads...

Error: 
Error: 
Error: 
Error: 
Error: 
Error: Failed to open sequence file Sporosarcina_1//total.faa for reading
Failed to open sequence file Sporosarcina_1//total.faa for reading

Failed to open sequence file Sporosarcina_1//total.faa for reading
Failed to open sequence file Sporosarcina_1//total.faa for reading

Error: 
Error: Failed to open sequence file Sporosarcina_1//total.faa for reading
Failed to open sequence file Sporosarcina_1//total.faa for reading

Failed to open sequence file Sporosarcina_1//total.faa for reading
Failed to open sequence file Sporosarcina_1//total.faa for reading

Error: 
Error: Failed to open sequence file Sporosarcina_1//total.faa for reading
Failed to open sequence file Sporosarcina_1//total.faa for reading

**(Error message sequence repeated until run terminated.)**

**Comment by ChaoLab** [comment]
Hi,
Can you try this:
`sudo perl METABOLIC-G.pl -in-gn Sporosarcina_1 -o Sporosarcina_1_out`
Note that the "/" was deleted.
