### ISSUE TITLE
Discrepancy between METABOLIC-C and anvi-estimate-metabolism

### ISSUE THREAD

**Issue by rzhan186** [AnantharamanLab/METABOLIC#70]
Dear METABOLIC developers, 

Thanks for the great tool! I just have two questions about the community-level nutrient cycling diagram. 

1. I have 430  MAGs, I realized that there is a discrepancy between results produced using Metabolic-C and the `anvi-estimate-metabolism` function from Anvio. For example, the “METABLIC_result” document generated by metabolic-c shows that only 30/430 MAGs have the KEGG module M00001, whereas results from `ansi-estimate-metabolism` shows that 391/430 MAGs have the module M00001, both using 0.75 as a completeness threshold. I am not sure why is there such a big difference. I noticed in the log file that the 'All_gene_collections.gene' file was empty, not sure if there is anything to do with this error. 

[=metabolic-C-output.txt](https://github.com/AnantharamanLab/METABOLIC/files/8490118/metabolic-C-output.txt)

ps: There is also a bowtie2 error, but since I am not particularly interested in the coverage of these MAGs, I just ignored this error, does ignoring the bowtie2 error have downstream consequences? 

2. Which pathways or modules were used to define the specific steps in the nutrient cycling diagram, and where can I find this information? For example, in the carbon cycling digram, there is a step called organic carbon oxidation, but I am not sure which specific modules define this step, I could not find "organic carbon oxidation" in the "METABOLIC_results" file. 

Thanks for your help! 

Rui

**Comment by patriciatran** [comment]
Hello @rzhan186 

I will answer your 2nd question and will see if @ChaoLab has an answer for your first question.

The HMM used for the pathways used in the figures can be found in the file called "R_pathways.txt" which is under the METABOLIC_database_and_template folder. I also attached it here. [R_pathways.txt](https://github.com/AnantharamanLab/METABOLIC/files/8491726/R_pathways.txt) . As can been seen in this file, there are many HMM usesd, mostly KEGG Gand TIGRfams, so you can link these KEGG and TIGRfams terms to the spreasheets in METABOLIC_results.xlsx . The category/reaction names match those in the figures.

Another thing to add when trying to interpret what is in R_pathways.txt and the METABOLIC_result spreadsheet, is that sometimes certain KEGG and TIGR have similar functions (eg: nitrogen fixation). For example, the R_pathways.txt tells us it uses TIGR01861.hmm,TIGR02931.hmm,TIGR02929.hmm,TIGR01282.hmm,TIGR01286.hmm,TIGR01860.hmm,TIGR02932.hmm,TIGR02930.hmm,TIGR01287.hmm, but the spreadsheet METABOLIC_results "HMMHitNum" if we filter "Function == N2 fixation", we can see the equivalencies under the headers "Hmm.file" and "Corresponding.KO".

The HMM file columns hints to us which HMM is used to determine each reaction/pathhway: if it starts with TIGR it's TIGRFAM, KO = KEGG, some gene name = METABOLIC custom HMM, PF is PFAM etc.

Hope this helps,

Patricia

**Comment by rzhan186** [comment]
Thank you @patriciatran for a comprehensive response! It seems to be this way but, just wanted to double-check that a MAG will be considered capable of a specific process (e.g. N2 fixation), as long as the MAG hits one of the HMMs belonging to that process?

**Comment by patriciatran** [comment]
Hello!

The default cutoff is 0.75 which means that 75% of Modules need to be present for the pathway to be called present. You can change this cutoff with the option -m-cutoff (number from 0 to 1) when you run METABOLIC.

Best,
Patricia

**Comment by patriciatran** [comment]
For your first questions regarding the discrepancy, it can be due to the whole set of KEGG hmms used, even with the same cutoff. I am not too familiar to compare all the KEGG ids that’s anvio used for that specific command, but since we also use other databases like tigrfam, pfams, the custom HMMs this could be the cause of the discrepancy. All those things would need to be compared

**Comment by rzhan186** [comment]
Hi @patriciatran, thank you I appreciate the timely reply! Sorry, I should have been more clear in my last question, I wasn’t referring to the KEGG modules, I was talking about the individual steps in the nutrient cycling diagram. 

Issue1:
The “R_pathway.txt” file contains the specific HMMs that correspond to steps in the nutrient cycling diagram. For example, there are 6 HMMs: soxX.hmm, soxY.hmm, soxZ.hmm, soxA.hmm; soxC.hmm, soxD.hmm that represents thiosulfate oxidation, my question is does METABOLIC-C consider a MAG as being capable of thiosulfate oxidation if the MAG has ANY of the above the HMMs? 

Issue2:
Also, if I search “thiosulfate oxidation” of the “Function” column in the “METABOLIC_results” file under HMMHitNum tab, I only saw 3 HMMs, which are soxB.hmm, soxY.hmm and soxC.hmm. This confuses me because some HMMs were missing in this column and there is another hmm (soxB.hmm) which wasn’t in the “R_Pathway.txt” file. 

Issue3
Is there a maximum number of MAGs that can be used as input for METABOLIC-C? I realized that when I use 430 MAGs together as input MAGs, it would show that lots of MAGs have no hits of any HMM. But if I pick only one MAGs with no HMM hits as input, the result show the MAG actually has lots of HMM hits. What could be the possible reason for this issue? 

I am not sure if it's an installation issue. Because our university cluster doesn't support Conda, I had to install all the dependencies manually. Do you think it's possible to test this input MAG ([GCA_000011005.1_ASM1100v1_genomic.fixed.txt](https://github.com/AnantharamanLab/METABOLIC/files/8497846/GCA_000011005.1_ASM1100v1_genomic.fixed.txt), please change the postfix from .txt to .faa) on your end, and paste the "METABOLIC_results" file here, so I can benchmark the results. 

Thank you, much appreciated!

**Comment by patriciatran** [comment]
Here are the results for your test file -- do you get the same thing?

[METABOLIC_result-4.xlsx](https://github.com/AnantharamanLab/METABOLIC/files/8498161/METABOLIC_result-4.xlsx)

**Comment by rzhan186** [comment]
Thanks for running the analysis! Here is my result. 
[METABOLIC_result.xlsx](https://github.com/AnantharamanLab/METABOLIC/files/8498211/METABOLIC_result.xlsx)

Strangely, it seems I only have 276 HMMs (rows) in my file, whereas 316 were reported from results on your end. HMM hits found to be present in my result were also reported as present in your results, but I just don't have "missing" HMMs on my end.

**Comment by patriciatran** [comment]
That is an interesting observation. Here is a comparison of the differences between the two.
[comparison_hmms_missing.xlsx](https://github.com/AnantharamanLab/METABOLIC/files/8500309/comparison_hmms_missing.xlsx) (red cells are duplicates between our two spreadsheets).

It looks like many Iron cycling, arsenic or metal cycling are missing or are under different names. Can you try downloading the latest METABOLIC databases following the commands here (https://github.com/AnantharamanLab/METABOLIC/blob/master/run_to_setup.sh).

For your info I have 24 557 `*.hmm` files in my `kofam/profiles` folder, and 195 `*.hmm` files in my `METABOLIC_hmm_db` folder.

**Comment by rzhan186** [comment]
Hi @patriciatran, I reinstalled METABOLIC following the procedure you provided, and managed to reproduce your results! 

However, one of the issues I mentioned earlier persisted, that is, METABOLIC wouldn't annotate some genomes when the input folder contains multiple genomes. I tried 430 MAGs in the beginning, and then lowered the number to 100 MAGs, but I still got the same error. 

For example, the metabolic result file ([METABOLIC_results_100MAGs.xlsx](https://github.com/AnantharamanLab/METABOLIC/files/8502527/METABOLIC_results_100MAGs.xlsx)) was produced using 100 MAGs as input, and included the genome (GCA_000011005.1_ASM1100v1_genomic.fixed) that I attached earlier, but none of the genes were annotated as PRESENT for this genome. And if you zoom out on the excel sheet (HMMHitNum), you can clearly see that when you scroll to the right, more genes get annotated, and the genomes on the left tend not to be annotated. 

Have you come across this issue before? What could be a possible reason? 

Thank you!

**Comment by patriciatran** [comment]
Hi @rzhan186 , thanks for the update! glad you can reproduce the results.

I have not seen this before, but some things to check are:

- In the spreasheet folder, what does the `METABOLI_result_worksheet1.tsv` file look like under `METABOLIC_resullts_each_spreadsheet/`? Do you see the same patterns? If yes then there is a problem with the script that makes the .tsv file, but if they are different, then something is wrong with the R script that is used to combined the files into the single metabolic_results.xlsx...
- Are the formats and contents of all the genomes the same (all have the same extension and that they indeed contain all amino acid sequences)?
- Are there other things in the genome input folder?

**Comment by rzhan186** [comment]
Hi @patriciatran! I finally found where the issue is, turned out that the contigs of all my genomes were named the same way such as  c_0001, c_0002. The program got confused when it encounters different genomes with identical contig names. The problem is simply solved by making the contig names unique to each genome, such as attaching the genome name at the end of the contig, e.g. c_0001_MAG1. 

Thank you for your help and patience!

**Comment by patriciatran** [comment]
Great! Good to hear this.

**Comment by JBuongio** [comment]
Hi y'all, 
I'm wondering if changing the threshold for module completeness fixed the issue of conflicting results between METABOLIC and anvi-estimate-metabolism. I am running into the same problem -- MAGs that anvi-estimate-metabolism says have 0.8-1 completeness of a module are coming up as 'absent' in METABOLIC (with the default cutoff of 0.75). 
Thanks!!

**Comment by ChaoLab** [comment]
> Hi y'all, I'm wondering if changing the threshold for module completeness fixed the issue of conflicting results between METABOLIC and anvi-estimate-metabolism. I am running into the same problem -- MAGs that anvi-estimate-metabolism says have 0.8-1 completeness of a module are coming up as 'absent' in METABOLIC (with the default cutoff of 0.75). Thanks!!

You might try to increase the module completeness cutoff of METABOLIC to have a look. While, I am not sure if they (anvi'o team) used the same method to assign the completeness.

**Comment by JBuongio** [comment]
Thanks! I dug into the steps that both programs use to define the module and they are different from each other. Not sure why that would be. 
Specifically: M00595 defined by METABOLIC is K17222+K17223+K17224-K17225-K08738+K17226+K17227.
For anvi-estimate-metabolism it is: K17222+K17223+K17224-K17225-K22622+K17226+K17227. 
The module definition according to KEGG is: K17222+K17223+K17224-K17225-K22622+K17226+K17227 (which matches anvi-estimate-metabolism's definition).

**Comment by JBuongio** [comment]
Thanks so much!!

**Comment by ChaoLab** [comment]
> Thanks so much!!

We have just updated the module information, you might have a try now

**Comment by JBuongio** [comment]
Wonderful, thanks a million! I'll give it a go!
