### ISSUE TITLE
Microbiome paper Fig.9

### ISSUE THREAD

**Issue by Qicheng-Xu** [AnantharamanLab/METABOLIC#71]
Hi,
I read the paper "METABOLIC: high-throughput profiling of microbial genomes for functional traits, metabolism, biogeochemistry, and community-scale functional networks" related to this tool, recently published in Microbiome. I am particularly interested in the Fig. 9 in the paper, that is Cell metabolism diagrams of specific genomes. Then I run the METABOLIC, it works well. However, I did not find the related file to draw "Cell metabolism diagrams". Could you tell me how to do this? Thank you.
Bests,
Qicheng

**Comment by patriciatran** [comment]
Hi @Qicheng-Xu , thanks for your comment. Unfortunately, those cell-level diagrams were done by hand (or rather by computer). There are no automatic code to make them...I have yet to find a bioinformatics program that makes these types of drawing, as they often take manual curation of the genomes, scrolling through the genes, selected a subset to draw on the figure.

**Comment by Qicheng-Xu** [comment]
Thank you for your reply.  I agree that the Figure was done by hand. My question is that, from which file/result generated by METABOLIC, can we draw this figure by hand. Where are these information from?
Bests.

**Comment by patriciatran** [comment]
Ah sorry for misunderstanding the comment! 
The output of the `METABOLIC_results.xlsx` file is the one, especially the page "KEGGModuleHit" in the column Module you'll find things like TCA cycle, transporters, etc. In the column Module Category you will find things like Central Carbon Metabolism, carbohydrate metabolism, lipid metabolism, etc.

**Comment by Qicheng-Xu** [comment]
Thank you! I fully understand the way you performed.
Bests.
