### ISSUE TITLE
Metabolic dbCAN based annotation results deviates greatly from dbCAN server based annotation

### ISSUE THREAD

**Issue by SOURAV-MUKHOPADHYAY** [AnantharamanLab/METABOLIC#73]
HI.
I experienced some issues with dbCAN annotation. The issue is whenever dbCAN based annotation on metabolic is being done on a group of MAGs, only GH and PLs are obtained as outputs, whereas the dbCAN server based annotation shows presence of GH, GT, PL and CBMs.  Eventually, the dbCAN hmm hits [metabolic] also show the presence of GTs and CBMs, however finally parsed output file [metabolic] is marked by the presence of GHs and PLs only for the same MAGs.

Thank you in advance for Clarifications and insights!!

**Comment by ChaoLab** [comment]
Hi @SOURAV-MUKHOPADHYAY In the pipeline of METABOLIC, we intentionally only kept GH and PL, since that GT and CBM do not specifically correspond to fixed groups of substrates, and GT and CBM sometimes have overlapped annotations with GH and PL.

**Comment by SOURAV-MUKHOPADHYAY** [comment]
Hi @ChaoLab 
Thank you for the clarifications. Appreciate it. Metabolic made life easier!!
