### ISSUE TITLE
Prodigal output file as nucleotides

### ISSUE THREAD

**Issue by oonakinn** [AnantharamanLab/METABOLIC#83]
Hi,

Would it be possible to extract the predicted coding sequences to an output file as nucleotides instead of amino acids? I see that this option is available for Prodigal.

Best,
Oona

**Comment by ChaoLab** [comment]
Sure, I can have a try

**Comment by ChaoLab** [comment]
I have updated METABOLIC-G/-C. Nucleotides will be generated in the same folder containing amino acids

**Comment by oonakinn** [comment]
Thank you so much! I am at the moment using the whole metagenome of a community (as contigs instead of MAGs) as input, so it took me a while to get the output from the run. But I can see the nucleotide sequences there now as well.
