### ISSUE TITLE
Install issue - can't locate parallel/forkmanager

### ISSUE THREAD

**Issue by cwood15** [AnantharamanLab/METABOLIC#85]
Followed the instructions for a full install and am running into the issue below. Does anyone know how to solve this?  

 Can't locate Parallel/ForkManager.pm in @INC (you may need to install the Parallel::ForkManager module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at METABOLIC-C.pl line 41.

Thank you
Claudia

**Comment by ChaoLab** [comment]
I found these online: 
https://stackoverflow.com/questions/16162539/how-to-install-parallelforkmanager-in-perl
https://stackoverflow.com/questions/59085861/how-to-install-the-parallelforkmanager-module

**Comment by cwood15** [comment]
Thanks I had tried those and was unable to get them to work because of not having sudo privileges on my server unfortunately. Did solve by just creating a conda environment and installing the missing package there using 

conda install -c bioconda perl-parallel-forkmanager 

Was then also missing Statistics::Descriptive module. Solved with:
conda install -c bioconda perl-statistics-descriptive
