### ISSUE TITLE
Discrepancy between hmm hits and KEGG modules in excell file

### ISSUE THREAD

**Issue by eertekin** [AnantharamanLab/METABOLIC#9]
Hello, thanks for the great tool. For some of the pathways, although none of the involved genes were found to be present by hmmsearch, in the kegg module hit table, the pathway is marked present. What may be the reason for this and which one should I consider to be accurate. 

Emine.

**Comment by ChaoLab** [comment]
In the software, we set a cutoff for assigning the presence of a pathway (default is 75%). So only over 75% of genes are present in a pathway, then we think this pathway is there. You could lower the cutoff by yourself.

**Comment by eertekin** [comment]
Hi,
Yes in my case it is the opposite. The genes are not there but the pathway is marked present. To be specific, for example, none of the Sox genes are identified but the thiosulfate oxidation by sox pathway is there.

**Comment by ChaoLab** [comment]
Hi, 
Can you look into the KO ids and search for their pathway KO ids? and then compare.

**Comment by eertekin** [comment]
Hey,

I am not sure I understood correctly but the module I am interested in is M00595 : the sox pathway. And none of the KOs involved, K17222,K7223 … etc. are found in the analysis but the pathway is there. I attached the excell output if it helps.

Thanks!
Emine 





Emine Ertekin, PhD

Johns Hopkins University
Krieger School of Arts and Sciences
Biology Department 
3400N Charles Street Mudd Hall 247 Baltimore, MD, US

**Comment by ChaoLab** [comment]
Hi,
I remember that sox genes are separated in Sheet 1. Can you send me back the resulted table?

**Comment by eertekin** [comment]
Which table the excell sheet? (Attached)





Emine Ertekin, PhD

Johns Hopkins University
Krieger School of Arts and Sciences
Biology Department 
3400N Charles Street Mudd Hall 247 Baltimore, MD, US

**Comment by ChaoLab** [comment]
Many thanks! I find that sox pathway is a very special one. We suggest the user use "Thiosulfate oxidation" in "FunctionHit" Sheet instead of the "KEGGModuleHit" Sheet. Due to that, for "KEGGModuleHit" result, if either one of Sox series genes is present, the whole pathway is present (which is not proper). Better to use the "FunctionHit" result. In your case, the "Thiosulfate oxidation" function is not present. 
Many thanks! We will add this to our Readme page.

**Comment by eertekin** [comment]
Ok, great. Thanks!
Emine
