### ISSUE TITLE
Read file for dereplicated MAGs

### ISSUE THREAD

**Issue by susheelbhanu** [AnantharamanLab/METABOLIC#94]
**Is your feature request related to a `challenge`? Please describe.**
I have a set of `dereplicated MAGs` that come from several samples. And the `read file` requires one set of reads per MAG for running METABOLIC.

**Questions**
1. Is it possible to provide multiple read-pairs per MAG?
2. If yes, should the forward reads go together followed by the reverse or do the read-pairs go together, i.e. what format will this take in the `read file reporting the paths`?
3. If no for question-1, what is the best way around this since a read file is **`required`**?

Thank you!
-Susheel

**Comment by ChaoLab** [comment]
1. Yes, you can set one set of reads (which come from one sample specifically) each time to get multiple results from individual runs. (https://github.com/AnantharamanLab/METABOLIC/wiki/METABOLIC-Usage#a-2nd-metabolic-c-run; this will guide you on how to save the same MAG profiling step for each time)
2. You can see the format of reads like this: https://github.com/AnantharamanLab/METABOLIC/wiki/METABOLIC-Usage#all-required-and-optional-flags. Please note that if you want to run multiple sets of reads separately, we will need to create mutiple read files. If you just want to combine all read sets together and use these as a whole to run the METABOLIC-C, you will just need to provide one read file with all the read pairs listed (one line for each set of reads and forward and reverse reads linked by a comma).

**Comment by susheelbhanu** [comment]
Great, thank you!
