### ISSUE TITLE
METABOLIC-C use both fas and faas as input?

### ISSUE THREAD

**Issue by CynthiaChibani** [AnantharamanLab/METABOLIC#97]
Hey There,
I am trying to run METABOLIC-C on a set of MAGs I generated from some samples with metatranscriptomes corresponding to the same samples.
I already have faas corresponding to all the MAGs fas bins that I used for multiple other analysis so for the sake of consistency in locus_tag ID, is there an option to use the same faas and not have metabolic-C run prodigal my bins?
Thanks in advance,
Cynthia

**Comment by ChaoLab** [comment]
This is doable by providing both the gene file and protein file in the same folder. You will have to mimic the files that will be generated by Prodigal itself. While this is only a custom use but not implemented in our script

**Comment by CynthiaChibani** [comment]
Thank you, I will give it a shot.
