### ISSUE TITLE
Metagenome sample numbering

### ISSUE THREAD

**Issue by B-1991-ing** [AnantharamanLab/METABOLIC#98]
Hi Zhichao,

The screenshot are my 6 metagenome fastq files, will the METABOLIC software recognise my "Sample2" as file1,  "Sample3" as file2,  "Sample4" as file3,   "Sample5" as file4,  "Sample6" as file5,  "Sample7" as file6?
 
<img width="880" alt="Screenshot 2022-08-30 at 11 21 27" src="https://user-images.githubusercontent.com/54441633/187400293-18d6193a-c918-4e9c-8b5f-2ae2b862a23d.png">

Best,

Bing

**Comment by ChaoLab** [comment]
No, METABOLIC will combined all the fastq files. If you want to get mapping results and subsequent networks, MW scores, etc, you will need to run them separately

**Comment by B-1991-ing** [comment]
Hi Zhichao,

The problem is that I put the my 55 MAGs and 6 metagenomes (**Sample2", "Sample3", "Sample4", "Sample5", "Sample6", "Sample7"**) as the input of the METABOLIC. But, in the  METABOLIC output, it gives me "Sample1", "Sample2", "Sample3", "Sample4", "Sample5", "Sample6". For example, All_gene_collections_mapped.**1**.sorted.bam, All_gene_collections_mapped.**2**.sorted.bam, All_gene_collections_mapped.**3**.sorted.bam, All_gene_collections_mapped.**4**.sorted.bam, All_gene_collections_mapped.**5**.sorted.bam, All_gene_collections_mapped.**6**.sorted.bam.
[All_gene_collections_mapped.depth copy.txt](https://github.com/AnantharamanLab/METABOLIC/files/9498410/All_gene_collections_mapped.depth.copy.txt)

**So, can I think as below?**
All_gene_collections_mapped.**1**.sorted.bam - my  Sample2
All_gene_collections_mapped.**2**.sorted.bam- my  Sample3
All_gene_collections_mapped.**3**.sorted.bam- my  Sample4
All_gene_collections_mapped.**4**.sorted.bam- my  Sample5
All_gene_collections_mapped.**5**.sorted.bam- my  Sample6
All_gene_collections_mapped.**6**.sorted.bam- my  Sample7

Bing

**Comment by ChaoLab** [comment]
Yes, the order is based on the raw numbers in your inputted read txt file. If Sample 2, 3, 4 ... 7 is the order of fastq files you placed, then yes to the corresponding relationship

**Comment by B-1991-ing** [comment]
Thank you very much for your reply, Zhichao.
